import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Provider from '@/components/Provider'
import Sidebar from '@/components/Sidebar'
import { MyProvider } from '@/context/MyContext'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Label App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='h-full relative'>
          
          <div className="hidden h-full md:flex md:w-72 md:flex-col md:fixed md:inset-y-0 z-[80] bg-gray-900">
            <Sidebar />
          </div>
          <main className="md:pl-72">
          <Provider>
            <MyProvider>
            {children}
            </MyProvider>
          </Provider>
          </main>
          
        </div>
        </body>
    </html>
  )
}
