import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Provider from '@/components/Provider'
import Sidebar from '@/components/Sidebar'
import { MyProvider } from '@/context/MyContext'
import { Toaster } from '@/components/ui/toaster'

//main layout


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Label App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='h-full relative w-screen'>
        <Provider>
        <MyProvider>
         {children}
         </MyProvider>
         </Provider>
        </div>
        <Toaster />
        </body>
    </html>
  )
}
